"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCodes = void 0;
exports.ErrorCodes = {
    // Auth
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
    AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
    AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
    // Tenant
    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
    TENANT_SUSPENDED: 'TENANT_SUSPENDED',
    TENANT_LIMIT_EXCEEDED: 'TENANT_LIMIT_EXCEEDED',
    TENANT_PRODUCT_NOT_ENTITLED: 'TENANT_PRODUCT_NOT_ENTITLED',
    // Validation
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    INVALID_INPUT: 'INVALID_INPUT',
    // Resources
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
    RESOURCE_LOCKED: 'RESOURCE_LOCKED',
    // Rate Limiting
    RATE_LIMITED: 'RATE_LIMITED',
    // POS
    POS_SESSION_EXPIRED: 'POS_SESSION_EXPIRED',
    POS_DRAWER_NOT_OPEN: 'POS_DRAWER_NOT_OPEN',
    POS_INSUFFICIENT_STOCK: 'POS_INSUFFICIENT_STOCK',
    POS_PAYMENT_FAILED: 'POS_PAYMENT_FAILED',
    // System
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
};
//# sourceMappingURL=error-codes.js.map