export declare const ErrorCodes: {
    readonly AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS";
    readonly AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED";
    readonly AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID";
    readonly AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS";
    readonly AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED";
    readonly AUTH_MFA_REQUIRED: "AUTH_MFA_REQUIRED";
    readonly TENANT_NOT_FOUND: "TENANT_NOT_FOUND";
    readonly TENANT_SUSPENDED: "TENANT_SUSPENDED";
    readonly TENANT_LIMIT_EXCEEDED: "TENANT_LIMIT_EXCEEDED";
    readonly TENANT_PRODUCT_NOT_ENTITLED: "TENANT_PRODUCT_NOT_ENTITLED";
    readonly VALIDATION_FAILED: "VALIDATION_FAILED";
    readonly INVALID_INPUT: "INVALID_INPUT";
    readonly RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND";
    readonly RESOURCE_CONFLICT: "RESOURCE_CONFLICT";
    readonly RESOURCE_LOCKED: "RESOURCE_LOCKED";
    readonly RATE_LIMITED: "RATE_LIMITED";
    readonly POS_SESSION_EXPIRED: "POS_SESSION_EXPIRED";
    readonly POS_DRAWER_NOT_OPEN: "POS_DRAWER_NOT_OPEN";
    readonly POS_INSUFFICIENT_STOCK: "POS_INSUFFICIENT_STOCK";
    readonly POS_PAYMENT_FAILED: "POS_PAYMENT_FAILED";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE";
    readonly EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR";
};
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
//# sourceMappingURL=error-codes.d.ts.map